### ISSUE TITLE
一点想法

### ISSUE THREAD

**Issue by ZHENFENG13** [titansec/OpenWAF#11]
最近都在学习WAF相关知识，目的是提高服务端的安全等级，一开始是比较了ModSecurity
和naxsi两个开源产品，实验后最终是选择了naxsi与nginx结合作为WAF，效果也还不错，但是naxsi好像没有流控的功能，接着又发现了verynginx这个开源WAF，用起来也挺好的，最后才是看到你这个项目，不过还没开始用，哈哈哈，第一感觉是README文档太多了，看的眼都花了，其次是感觉文档里并没有突出的展现咱们这个项目的优势和主要功能，反而更多的都是一些参数介绍，如果我没有看你代码的话，我真的挺难从文档中得到答案或者解答疑惑，一点小建议，接下来几天会认真看一下项目的，加油！

**Comment by miracleqi** [comment]
感谢你的宝贵建议，我会努力的。希望OpenWAF能够给你提供帮助。
