### ISSUE TITLE
编译Openresty出现问题，按照教程来的

### ISSUE THREAD

**Issue by aa1215018028** [titansec/OpenWAF#14]
Compiled with g++ [x86_64-unknown-linux-gnu]
Please see http://www.swig.org for reporting bugs and further information
swig -lua -Wall -Wextra libinjection.i
libinjection_sqli.h:192: Warning(322): Redundant redeclaration of 'version' (Renamed from 'libinjection_version'),
libinjection.h:39: Warning(322): previous declaration of 'version' (Renamed from 'libinjection_version').
cc -O0 -g -Wall -Wextra -Wformat=2 -fPIC -fno-common -I. -I/opt/openresty/build/luajit-root/usr/local/openrestyforopenwaf/luajit/include/luajit-2.1 \
	-shared -Wl,-soname,libinjection.so libinjection_wrap.c libinjection_sqli.c libinjection_html5.c libinjection_xss.c -o libinjection.so
libinjection_wrap.c:2698: error: array type has incomplete element type
gmake[2]: *** [libinjection.so] Error 1
gmake[2]: Leaving directory `/opt/openresty/build/lua-libinjection-3.9.1/lua'
gmake[1]: *** [install] Error 2
gmake[1]: Leaving directory `/opt/openresty/build/lua-libinjection-3.9.1'
gmake: *** [all] Error 2

**Comment by miracleqi** [comment]
抱歉这几天经常出差，如果我没有及时反馈信息，可在群里询问他人

**Comment by lianfeng30** [comment]
@miracleqi  群号是多少？
.zip .apk .exe下载被拦截，该如何处理？ 谢谢

**Comment by lianfeng30** [comment]
@miracleqi 
访问的URL: http://www.aaa.mobi/download/6.1.9.6.apk 
触发的事件类型: exception.req.access_rule

这样子
怎么办？

**Comment by hubowestlife** [comment]
`ln -sf luajit-2.1.0-beta2 /opt/openresty-1.11.2.2/build/luajit-root//usr/local/openresty/luajit/bin/luajit
==== Successfully installed LuaJIT 2.1.0-beta2 to /usr/local/openresty/luajit ====
export LUAJIT_LIB='/opt/openresty-1.11.2.2/build/luajit-root/usr/local/openresty/luajit/lib'
export LUAJIT_INC='/opt/openresty-1.11.2.2/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1'
cd ..
patching the resty script with hard-coded nginx binary path...
failed to patch /opt/openresty-1.11.2.2/build/resty-cli-0.16/bin/resty: the line 'my $nginx_path' was not found.`
