### ISSUE TITLE
正常.zip .apk .exe下载被拦截，该如何处理？

### ISSUE THREAD

**Issue by lianfeng30** [titansec/OpenWAF#15]
@miracleqi 群号是多少？
.zip .apk .exe下载被拦截，该如何处理？ 谢谢

@miracleqi
访问的URL: http://www.aaa.mobi/download/6.1.9.6.apk
触发的事件类型: exception.req.access_rule

这样子
怎么办？

**Comment by miracleqi** [comment]
群号：579790127
