### ISSUE TITLE
openwaf如何增加host头信息

### ISSUE THREAD

**Issue by bwkang** [titansec/OpenWAF#16]
目前的结构是接入层---haproxy--docker集群，haproxy根据host分发至不同的容器，之前使用nginx的时候可以通过添加 add_header Host "www.xxx.com"使后端分发正常，刚接触openwaf，不知道这个需要如何添加

**Comment by miracleqi** [comment]
openwaf 依然可以在 nginx 配置文件中使用 add_header （提示：add_header 支持变量）
openwaf 支持使用原有的 nginx 配置文件，只需在要防护的 server 添加 openwaf 的防护即可
详细可参考https://github.com/titansec/OpenWAF/blob/master/doc/%E8%BD%BB%E6%9D%BE%E7%8E%A9%E8%BD%ACOpenWAF%E4%B9%8B%E5%85%A5%E9%97%A8%E7%AF%87.md#使用自己原有的nginx配置

使用 openwaf 后，如果想简化 nginx 配置，可以进群讨论，群号：579790127
