### ISSUE TITLE
openwaf安装后远程访问出现502 bad gateway

### ISSUE THREAD

**Issue by xiaosaoba** [titansec/OpenWAF#2]
openwaf安装后远程访问出现502 bad gateway，本地curl是可以打开，但是通过远程ip访问出现502 ，ubuntu16..04,selinux和iptables已经关闭

**Comment by miracleqi** [comment]
出现502有四种可能
1. 网络不通，或没有后端web服务器（能够通过curl访问到，说明不是此问题）
2. 网络防火墙拦截（selinux和iptables已关闭，说明不是此问题）
3. OpenWAF的接入规则配置无效（通过你发给我的配置，显示你未配置forward_addr和forward_port）
4. nginx配置无效（balancer_by_lua与content_by_lua不能同时使用，否则只有content_by_lua生效）
