### ISSUE TITLE
目前有管理界面了么

### ISSUE THREAD

**Issue by meigea** [titansec/OpenWAF#23]
我觉得这个项目，非常好，我目前用得是`modsecurity3+nginx+crs302`， 配置都是文本编辑替换，我看你这个都是 json 处理， 优化特别大，而且模块分工明确，修改耦合性低一些；；期待有更好的版本。

**Comment by linsir** [comment]
[OpenWAF-UI](https://github.com/titansec/OpenWAF-UI)
