### ISSUE TITLE
默认正常请求被拦截

### ISSUE THREAD

**Issue by starnightcyber** [titansec/OpenWAF#28]
您好，我是在Ubuntu虚拟机上搭建了一个DVWA（80端口）来测试OpenWAF。
直接访问80端口，可正常访问dvwa。
使用的是OpenWAF的默认配置文件/etc/ngx_openwaf.conf ，仅改了默认监听端口为8080。
```
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      29281/ngx_openwaf.c
tcp6       0      0 :::8080                 :::*                    LISTEN      29281/ngx_openwaf.c
tcp6       0      0 :::80                   :::*                    LISTEN      1957/apache2
```
twaf_access_rule.json修改第一条接入规则的"forward_addr"和“forward_port”值。
```
{
  "host":"^.*$",
  "path":"/",
  "uuid":"test_uuid1",
  "forward":"test",
  "client_ssl":false,
  "server_ssl":false,
  "forward_addr":"127.0.0.1",
  "forward_port":80,
  "policy": "twaf_policy_conf"
}
```
我理解的是访问openresty 8080端口，然后代理到80端口。用本机ip和127.0.0.1都试过了。
直接访问8080端口即被拦截，我认为正常应该代理到dvwa的80端口吧？
![image](https://user-images.githubusercontent.com/19260696/74811932-7b91ae00-532d-11ea-8cd3-c49f6d3e459b.png)

**Comment by miracleqi** [comment]
你好，发布端口默认80或443，应该配置port为8080
详细请参考https://github.com/titansec/OpenWAF#port

**Comment by starnightcyber** [comment]
> 你好，发布端口默认80或443，应该配置port为8080
> 详细请参考https://github.com/titansec/OpenWAF#port

好的，修改默认端口可以访问了，多谢！
