### ISSUE TITLE
关于日志记录问题

### ISSUE THREAD

**Issue by starnightcyber** [titansec/OpenWAF#29]
您好，请问日志记录功能近期是否已经实现了？
看了下，在您的TODO list里。

**Comment by miracleqi** [comment]
哪一个？日志写入本地文件么？

**Comment by miracleqi** [comment]
V1.0.0β中所有的功能变更和性能优化均已在2月14日更新至github，TODO里提到的，只是更新相关的描述文档，这些文档基本在2月19日已完成，详见https://github.com/titansec/OpenWAF/blob/master/Changelog.md

**Comment by starnightcyber** [comment]
日志写入本地文件
