### ISSUE TITLE
GeoIP_continent_by_id stack traceback:

### ISSUE THREAD

**Issue by An93l** [titansec/OpenWAF#3]
nginx: the configuration file /etc/ngx_openwaf.conf syntax is ok
nginx: [error] init_by_lua_file error: error loading module 'geoip.country' from file '/usr/local/openresty/lualib/geoip/country.so':
	/usr/local/openresty/lualib/geoip/country.so: undefined symbol: GeoIP_continent_by_id
stack traceback:
	[C]: at 0x7fa57dd7d080
	[C]: in function 'require'
	/opt/OpenWAF/lib/twaf/twaf_conf.lua:11: in main chunk
	[C]: in function 'require'
	/opt/OpenWAF/app/twaf_init.lua:6: in main chunk
nginx: configuration file /etc/ngx_openwaf.conf test failed

**Comment by miracleqi** [comment]
当前，Ubuntu用户会遇到此问题
解决方法：在编译openresty时，带上--with-http_geoip_module
重新编译即可
