### ISSUE TITLE
cc攻击压测的时候会出现下500错误，然后就会正常

### ISSUE THREAD

**Issue by An93l** [titansec/OpenWAF#4]
2017/04/06 17:48:56 [error] 1625#0: *46599 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/logger/socket.lua:112: attempt to index local 'sock' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/openresty/lualib/resty/logger/socket.lua: in function '_do_connect'
	/usr/local/openresty/lualib/resty/logger/socket.lua:158: in function '_connect'
	/usr/local/openresty/lualib/resty/logger/socket.lua:209: in function '_do_flush'
	/usr/local/openresty/lualib/resty/logger/socket.lua:293: in function </usr/local/openresty/lualib/resty/logger/socket.lua:261>, context: ngx.timer, client: x.x.x.x, server: 0.0.0.0:80

**Comment by miracleqi** [comment]
您报的sock （a nil value） 是由于ulimit -n 为1024，CC压测当nginx连接数超过1024时，error.log中就出现以下错误
    accept4() failed (24: Too many open files)
    socket() failed (24: Too many open files)
使用 ulimit -n 655350 可以把打开文件数设置足够大，同时修改nginx.conf ， 添加 worker_rlimit_nofile 655350； 这样就可以解决Nginx连接过多的问题，Nginx就可以支持高并发。

注意： 用ulimit -n 655350 修改只对当前的shell有效，退出后失效。

若要令修改ulimits的数值永久生效,则必须修改配置文档,可以给ulimit修改命令放入/etc/profile里面
