### ISSUE TITLE
这个waf 能多台集群吗？

### ISSUE THREAD

**Issue by m1911** [titansec/OpenWAF#5]
这个waf 能多台集群吗？

**Comment by miracleqi** [comment]
当然可以，通过集群也可提升性能

**Comment by m1911** [comment]
没看到相关配置教程啊

**Comment by miracleqi** [comment]
你可以查找nginx集群或者openresty集群

**Comment by m1911** [comment]
那 openwaf 的规则怎么同步啊

**Comment by miracleqi** [comment]
规则同步需要外部控制，openwaf目前没有开源这部分

**Comment by m1911** [comment]
@miracleqi 那这个部分会开源吗？要是开源大概什么时候能开源？

**Comment by miracleqi** [comment]
很抱歉，这部分暂时没有打算开源
你可以根据需求，自己编写
