### ISSUE TITLE
希望能出一个Tengine的安装配置文档

### ISSUE THREAD

**Issue by mojie126** [titansec/OpenWAF#6]
希望能出一个Tengine的安装配置文档...谢谢...

**Comment by miracleqi** [comment]
群里有人试过用nginx + lua + lua_nginx_module + OpenWAF
你可以试着问他如何搭建环境的

**Comment by mojie126** [comment]
嗯，弄好了，但是貌似不支持HTTPS…？加载了那个twaf_cert的lua和set $twaf_https 1，但是没用…

**Comment by miracleqi** [comment]
HTTPS问题已转至issues #7
