### ISSUE TITLE
centOS +nginx的环境下怎么安装部署？

### ISSUE THREAD

**Issue by yanggongwang** [titansec/OpenWAF#9]
Hi，国内CentOS 6+nginx的环境并不少，请问怎么在这些环境中部署？谢谢

**Comment by miracleqi** [comment]
https://github.com/openresty/lua-nginx-module#installation
OpenWAF需要openresty的lua-nginx-module模块，nginx安装此模块，可按上面文章进行安装
接着安装OpenWAF所需的nginx第三方模块（按照nginx第三方模块安装方法安装即可）
然后即可使用OpenWAF

**Comment by miracleqi** [comment]
当前正在将OpenWAF所需的第三方nginx模块，支持动态加载，这样不需手动添加第三方模块

**Comment by mojie126** [comment]
这个功能好，这样我就可以不需要OpenResty而直接使用Tengine+lua了...
